### ISSUE TITLE
Please do a decent code review before accepting pull requests

### ISSUE THREAD

**Issue by yifeikong** [gaojiuli/gain#22]
As this project has already got nearly 800 stars on GitHub, please be responsible for each pull request you accept. the code in result directory is not qualified enough to be accepted.

**Comment by gaojiuli** [comment]
Thanks for your suggestion. I had reviewed the code when he pull request the first time but forgot to add review comments when he pull request the second time, because he add tests and all tests passed and I had run them in my ubuntu.

Anyway, I'd merge the pull request carefully the next time. Code review is important. Thanks for your joining.
